# Generated by Django 4.1.7 on 2023-03-28 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_author_alter_blogpost_mod_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
