# Generated by Django 4.1.7 on 2023-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_mod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
